on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

name: build-deploy
jobs:
  check_and_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: publish packages
        uses: menduz/oddish-action@master
        with:
          registry-url: 'https://registry.npmjs.org'
          access: public
          ## sign the deployment
          #provenance: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}